project: 
  type: website
  output-dir: "." 

website:
  title: "Josh Lefkowicz"
  navbar:
    # background: "#1c4982"
    pinned: true
    left:
      - text: Blog
        href: blog-listing.qmd
      - text: Python Basic
        href: danl-210-python-basic.ipynb
      - text: Project
        href: danl_proj_nba.ipynb
      - text: Python Data Analysis
      
            
  page-footer: 
    center: "Powered with GitHub, Quarto, and Jupyter Notebook<br>© Josh Lefkowicz, 2025"

format:
  html:
    theme: 
      light: flatly # flatly sandstone yeti united litera journal
      dark: darkly #  darkly cyborg slate solra superhero
    mainfont: system-ui; 
    highlight-style: atom-one  # atom-one espresso
    css: styles.css
    toc: false
    include-after-body: target_blank.html

